# Generated by Django 4.2.7 on 2026-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cnpj",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="cliente",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="clientes/logos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="funcao",
            field=models.CharField(
                blank=True,
                choices=[("viewer", "Apenas ver")],
                default="",
                max_length=30,
            ),
        ),
    ]
