# Generated by Django 4.2.7 on 2026-02-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_cliente_atualizado_em_cliente_cnpj_cliente_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("colaborador", "Colaborador"),
                    ("cliente", "Cliente"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
