# Generated by Django 4.2.7 on 2026-02-06 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_add_colaborador_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Falhou"),
                            ("piece_deleted", "Peca Deletada"),
                            ("piece_created", "Peca Criada"),
                            ("campaign_created", "Campanha Criada"),
                            ("campaign_deleted", "Campanha Deletada"),
                            ("campaign_updated", "Campanha Atualizada"),
                            ("asset_uploaded", "Asset Enviado"),
                            ("user_created", "Usuario Criado"),
                            ("user_updated", "Usuario Atualizado"),
                            ("user_deleted", "Usuario Deletado"),
                            ("cliente_created", "Cliente Criado"),
                            ("cliente_updated", "Cliente Atualizado"),
                            ("media_plan_uploaded", "Plano de Midia Enviado"),
                            ("contract_uploaded", "Contrato Enviado"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="accounts.cliente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="accounts_au_event_t_d9f6e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "created_at"],
                name="accounts_au_user_id_3e4e4d_idx",
            ),
        ),
    ]
