# Generated by Django 4.2.7 on 2026-02-10 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alert"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="accounts_au_event_t_1d4237_idx",
            old_name="accounts_au_event_t_d9f6e0_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="accounts_au_user_id_7b1069_idx",
            old_name="accounts_au_user_id_3e4e4d_idx",
        ),
    ]
