# Generated by Django 4.2.7 on 2026-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0007_rename_accounts_au_event_t_d9f6e0_idx_accounts_au_event_t_1d4237_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Falhou"),
                    ("piece_deleted", "Peca Deletada"),
                    ("piece_created", "Peca Criada"),
                    ("campaign_created", "Campanha Criada"),
                    ("campaign_deleted", "Campanha Deletada"),
                    ("campaign_updated", "Campanha Atualizada"),
                    ("asset_uploaded", "Asset Enviado"),
                    ("user_created", "Usuario Criado"),
                    ("user_updated", "Usuario Atualizado"),
                    ("user_deleted", "Usuario Deletado"),
                    ("cliente_created", "Cliente Criado"),
                    ("cliente_updated", "Cliente Atualizado"),
                    ("media_plan_uploaded", "Plano de Midia Enviado"),
                    ("contract_uploaded", "Contrato Enviado"),
                    ("password_reset_requested", "Recuperacao de Senha Solicitada"),
                    ("password_reset_completed", "Senha Redefinida"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["cliente", "lido", "-criado_em"], name="alert_cliente_lido_idx"
            ),
        ),
    ]
