# Generated by Django 4.2.7 on 2026-03-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_perf_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.JSONField(blank=True, default=dict)),
                ("metricas", models.JSONField(blank=True, default=dict)),
                ("alertas", models.JSONField(blank=True, default=list)),
                ("financeiro", models.JSONField(blank=True, default=dict)),
                ("estrutura", models.JSONField(blank=True, default=dict)),
                ("ia", models.JSONField(blank=True, default=dict)),
                ("seguranca", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração do Site",
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Falhou"),
                    ("piece_deleted", "Peca Deletada"),
                    ("piece_created", "Peca Criada"),
                    ("campaign_created", "Campanha Criada"),
                    ("campaign_deleted", "Campanha Deletada"),
                    ("campaign_updated", "Campanha Atualizada"),
                    ("asset_uploaded", "Asset Enviado"),
                    ("user_created", "Usuario Criado"),
                    ("user_updated", "Usuario Atualizado"),
                    ("user_deleted", "Usuario Deletado"),
                    ("cliente_created", "Cliente Criado"),
                    ("cliente_updated", "Cliente Atualizado"),
                    ("cliente_deleted", "Cliente Deletado"),
                    ("media_plan_uploaded", "Plano de Midia Enviado"),
                    ("contract_uploaded", "Contrato Enviado"),
                    ("password_reset_requested", "Recuperacao de Senha Solicitada"),
                    ("password_reset_completed", "Senha Redefinida"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
