# Generated by Django 4.2.7 on 2026-03-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_site_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
    ]
