# Generated by Django 4.2.7 on 2026-03-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("insight", "Insight"),
                            ("alert", "Alerta"),
                            ("recommendation", "Recomendação"),
                            ("summary", "Resumo Executivo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("severity", models.CharField(blank=True, default="", max_length=20)),
                ("title", models.CharField(max_length=300)),
                ("text", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dismissed", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="accounts.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Insight",
                "verbose_name_plural": "AI Insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cliente", "date_from", "date_to"],
                        name="aiinsight_cliente_dates_idx",
                    )
                ],
            },
        ),
    ]
