# Generated by Django 4.2.7 on 2026-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_ai_insight_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="whatsapp",
            field=models.CharField(
                blank=True, default="", help_text="Ex: 5511999999999", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="whatsapp_reports",
            field=models.BooleanField(
                default=False, help_text="Enviar relatórios periódicos via WhatsApp"
            ),
        ),
    ]
