# Generated by Django 4.2.7 on 2026-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_cliente_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="email_reports",
            field=models.BooleanField(
                default=False, help_text="Enviar relatórios periódicos por e-mail"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="report_emails",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E-mails para relatórios (um por linha)",
            ),
        ),
    ]
