# Generated by Django 4.2.7 on 2026-04-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_cliente_report_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="dashon_hidden_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="IDs de modulos do DashON ocultos para usuarios nao-admin deste cliente",
            ),
        ),
    ]
