# Generated by Django 4.2.7 on 2026-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_cliente_dashon_hidden_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="consolidated_hidden_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="IDs de modulos do Consolidated ON ocultos para usuarios nao-admin deste cliente",
            ),
        ),
    ]
