# Generated by Django 4.2.7 on 2026-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_cliente_consolidated_hidden_modules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Falhou"),
                    ("piece_deleted", "Peca Deletada"),
                    ("piece_created", "Peca Criada"),
                    ("campaign_created", "Campanha Criada"),
                    ("campaign_deleted", "Campanha Deletada"),
                    ("campaign_updated", "Campanha Atualizada"),
                    ("asset_uploaded", "Asset Enviado"),
                    ("user_created", "Usuario Criado"),
                    ("user_updated", "Usuario Atualizado"),
                    ("user_deleted", "Usuario Deletado"),
                    ("cliente_created", "Cliente Criado"),
                    ("cliente_updated", "Cliente Atualizado"),
                    ("cliente_deleted", "Cliente Deletado"),
                    ("media_plan_uploaded", "Plano de Midia Enviado"),
                    ("contract_uploaded", "Contrato Enviado"),
                    ("password_reset_requested", "Recuperacao de Senha Solicitada"),
                    ("password_reset_completed", "Senha Redefinida"),
                    ("financial_updated", "Dados Financeiros Atualizados"),
                    ("financial_deleted", "Dados Financeiros Deletados"),
                    ("visibility_changed", "Visibilidade Alterada"),
                    ("efficiency_updated", "Eficiencia Atualizada"),
                    ("efficiency_deleted", "Eficiencia Deletada"),
                    ("region_updated", "Regioes Atualizadas"),
                    ("campaign_status", "Status Campanha Alterado"),
                    ("settings_updated", "Configuracoes Atualizadas"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
