# Generated by Django 4.2.7 on 2026-02-10 01:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "accounts",
            "0007_rename_accounts_au_event_t_d9f6e0_idx_accounts_au_event_t_1d4237_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAdsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        help_text="Google Ads Customer ID (xxx-xxx-xxxx)", max_length=20
                    ),
                ),
                (
                    "descriptive_name",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "_access_token",
                    models.TextField(blank=True, db_column="access_token", default=""),
                ),
                (
                    "_refresh_token",
                    models.TextField(blank=True, db_column="refresh_token", default=""),
                ),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_accounts",
                        to="accounts.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Google Ads",
                "verbose_name_plural": "Contas Google Ads",
                "unique_together": {("cliente", "customer_id")},
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Em execução"),
                            ("success", "Sucesso"),
                            ("error", "Erro"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("campaigns_synced", models.IntegerField(default=0)),
                ("metrics_synced", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="integrations.googleadsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de sincronização",
                "verbose_name_plural": "Logs de sincronização",
                "ordering": ["-started_at"],
            },
        ),
    ]
