# Generated by Django 4.2.7 on 2026-02-11 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0007_rename_accounts_au_event_t_d9f6e0_idx_accounts_au_event_t_1d4237_idx_and_more",
        ),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaAdsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_account_id",
                    models.CharField(
                        help_text="Meta Ads Account ID (act_XXXXXXXXX)", max_length=30
                    ),
                ),
                (
                    "descriptive_name",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "_access_token",
                    models.TextField(
                        blank=True, db_column="meta_access_token", default=""
                    ),
                ),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_ads_accounts",
                        to="accounts.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Meta Ads",
                "verbose_name_plural": "Contas Meta Ads",
                "unique_together": {("cliente", "ad_account_id")},
            },
        ),
        migrations.CreateModel(
            name="MetaSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Em execucao"),
                            ("success", "Sucesso"),
                            ("error", "Erro"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("campaigns_synced", models.IntegerField(default=0)),
                ("metrics_synced", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="integrations.metaadsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de sincronizacao Meta",
                "verbose_name_plural": "Logs de sincronizacao Meta",
                "ordering": ["-started_at"],
            },
        ),
    ]
