# Generated by Django 4.2.7 on 2026-02-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_cliente_atualizado_em_cliente_cnpj_cliente_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "total_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Sao_Paulo", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("on", "ON"), ("off", "OFF")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="accounts.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campanha",
                "verbose_name_plural": "Campanhas",
            },
        ),
        migrations.CreateModel(
            name="PlacementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=100)),
                ("channel", models.CharField(blank=True, default="", max_length=100)),
                ("program", models.CharField(blank=True, default="", max_length=150)),
                (
                    "property_text",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "format_text",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("duration_sec", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_lines",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de mídia",
                "verbose_name_plural": "Linhas de mídia",
            },
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=250)),
                ("duration_sec", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peça",
                "verbose_name_plural": "Peças",
                "unique_together": {("campaign", "code")},
            },
        ),
        migrations.CreateModel(
            name="CreativeAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="campaigns/assets/")),
                ("preview_url", models.URLField(blank=True, default="")),
                ("thumb_url", models.URLField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="campaigns.piece",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset criativo",
                "verbose_name_plural": "Assets criativos",
            },
        ),
        migrations.CreateModel(
            name="ContractUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="campaigns/contracts/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_uploads",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de upload",
                "verbose_name_plural": "Contratos de upload",
            },
        ),
        migrations.CreateModel(
            name="PlacementDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("insertions", models.PositiveIntegerField(default=0)),
                (
                    "placement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="campaigns.placementline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dia de veiculação",
                "verbose_name_plural": "Dias de veiculação",
                "unique_together": {("placement_line", "date")},
            },
        ),
    ]
