# Generated by Django 4.2.7 on 2026-02-03 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="media_type",
            field=models.CharField(
                choices=[("online", "ONLINE"), ("offline", "OFFLINE")],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="creativeasset",
            name="checksum",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="piece",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="piece",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="placementday",
            name="clicks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementday",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="placementday",
            name="impressions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementline",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementline",
            name="external_ref",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="placementline",
            name="media_channel",
            field=models.CharField(
                choices=[
                    ("tv_aberta", "TV_ABERTA"),
                    ("paytv", "PAYTV"),
                    ("radio", "RADIO"),
                    ("ooh", "OOH"),
                    ("jornal", "JORNAL"),
                    ("meta", "META"),
                    ("google", "GOOGLE"),
                    ("youtube", "YOUTUBE"),
                    ("display", "DISPLAY"),
                    ("search", "SEARCH"),
                    ("social", "SOCIAL"),
                    ("other", "OTHER"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="placementline",
            name="media_type",
            field=models.CharField(
                choices=[("online", "ONLINE"), ("offline", "OFFLINE")],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="placementline",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("finished", "Finished"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlacementCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_creatives",
                        to="campaigns.piece",
                    ),
                ),
                (
                    "placement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_creatives",
                        to="campaigns.placementline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo linha x peça",
                "verbose_name_plural": "Vínculos linha x peça",
                "unique_together": {("placement_line", "piece")},
            },
        ),
    ]
