# Generated by Django 4.2.7 on 2026-02-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_campaign_created_by_campaign_media_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaPlanUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="campaigns/media_plans/")),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_plan_uploads",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload de plano de mídia",
                "verbose_name_plural": "Uploads de plano de mídia",
            },
        ),
    ]
