# Generated by Django 4.2.7 on 2026-02-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_mediaplanupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_name", models.CharField(max_length=200)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(default="#6366f1", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_investments",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investimento por Região",
                "verbose_name_plural": "Investimentos por Região",
                "ordering": ["order", "region_name"],
                "unique_together": {("campaign", "region_name")},
            },
        ),
    ]
