# Generated by Django 4.2.7 on 2026-02-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_add_region_investment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("html5", "HTML5"),
                ],
                max_length=20,
            ),
        ),
    ]
