# Generated by Django 4.2.7 on 2026-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0005_add_html5_piece_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placementline",
            name="external_ref",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["cliente", "status"], name="campaign_cliente_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["cliente", "start_date", "end_date"],
                name="campaign_cliente_dates_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="placementday",
            index=models.Index(fields=["date"], name="placementday_date_idx"),
        ),
        migrations.AddIndex(
            model_name="placementline",
            index=models.Index(
                fields=["campaign", "media_channel"],
                name="placement_campaign_channel_idx",
            ),
        ),
    ]
