# Generated by Django 4.2.7 on 2026-03-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_financial_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=250)),
                ("headline", models.CharField(blank=True, default="", max_length=250)),
                ("description", models.TextField(blank=True, default="")),
                ("final_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("responsive_search", "Pesquisa Responsiva"),
                            ("responsive_display", "Display Responsivo"),
                            ("video", "Vídeo"),
                            ("image", "Imagem"),
                            ("shopping", "Shopping"),
                            ("app", "App"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("external_ref", models.CharField(db_index=True, max_length=120)),
                ("platform", models.CharField(default="google", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Ativo"),
                            ("paused", "Pausado"),
                            ("removed", "Removido"),
                        ],
                        default="enabled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Anúncio",
                "verbose_name_plural": "Anúncios",
            },
        ),
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("external_ref", models.CharField(db_index=True, max_length=120)),
                ("platform", models.CharField(default="google", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Ativo"),
                            ("paused", "Pausado"),
                            ("removed", "Removido"),
                        ],
                        default="enabled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "placement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_groups",
                        to="campaigns.placementline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Anúncios",
                "verbose_name_plural": "Grupos de Anúncios",
            },
        ),
        migrations.CreateModel(
            name="AdDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="campaigns.ad",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ad",
            name="ad_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="campaigns.adgroup",
            ),
        ),
        migrations.CreateModel(
            name="AdGroupDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="campaigns.adgroup",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["date"], name="adgroupday_date_idx")],
                "unique_together": {("ad_group", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="adgroup",
            index=models.Index(
                fields=["platform", "external_ref"], name="adgroup_plat_ref_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adgroup",
            unique_together={("placement_line", "external_ref")},
        ),
        migrations.AddIndex(
            model_name="adday",
            index=models.Index(fields=["date"], name="adday_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="adday",
            unique_together={("ad", "date")},
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["platform", "external_ref"], name="ad_plat_ref_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ad",
            unique_together={("ad_group", "external_ref")},
        ),
    ]
