# Generated by Django 4.2.7 on 2026-03-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0008_ad_groups_and_ads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placementline",
            name="media_channel",
            field=models.CharField(
                choices=[
                    ("tv_aberta", "TV_ABERTA"),
                    ("paytv", "PAYTV"),
                    ("radio", "RADIO"),
                    ("ooh", "OOH"),
                    ("jornal", "JORNAL"),
                    ("meta", "META"),
                    ("google", "GOOGLE"),
                    ("youtube", "YOUTUBE"),
                    ("display", "DISPLAY"),
                    ("search", "SEARCH"),
                    ("social", "SOCIAL"),
                    ("tiktok", "TIKTOK"),
                    ("linkedin", "LINKEDIN"),
                    ("dv360", "DV360"),
                    ("dv360_youtube", "DV360_YOUTUBE"),
                    ("dv360_spotify", "DV360_SPOTIFY"),
                    ("dv360_eletromid", "DV360_ELETROMIDIA"),
                    ("dv360_netflix", "DV360_NETFLIX"),
                    ("dv360_globoplay", "DV360_GLOBOPLAY"),
                    ("dv360_admooh", "DV360_ADMOOH"),
                    ("other", "OTHER"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
