# Generated by Django 4.2.7 on 2026-04-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0009_add_digital_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adday",
            name="clicks",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="adday",
            name="impressions",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="adgroupday",
            name="clicks",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="adgroupday",
            name="impressions",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="mediaefficiency",
            name="circulacao",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediaefficiency",
            name="impactos",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="placementday",
            name="clicks",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="placementday",
            name="impressions",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="placementday",
            name="insertions",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
