# Generated by Django 4.2.7 on 2026-04-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0010_alter_adday_clicks_alter_adday_impressions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialsummary",
            name="client_visible",
            field=models.BooleanField(
                default=False, help_text="Se True, cliente pode ver a página financeira"
            ),
        ),
        migrations.AddField(
            model_name="financialsummary",
            name="visibility",
            field=models.JSONField(
                blank=True, default=dict, help_text="Campos visíveis ao cliente"
            ),
        ),
    ]
