from django.urls import path

from . import views


app_name = "web"


urlpatterns = [
    path("", views.root, name="root"),
    path("login/", views.login_view, name="login"),
    path("login/<slug:cliente_slug>/", views.login_cliente_view, name="login_cliente"),
    path("logout/", views.logout_view, name="logout"),
    path("administracao/", views.administracao, name="administracao"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("timeline-campanhas/", views.timeline_campanhas, name="timeline_campanhas"),
    path("campanhas/", views.grupo_campanhas, name="grupo_campanhas"),
    path("campanhas/<int:cliente_id>/", views.campanhas_cliente, name="campanhas_cliente"),
    path("campanhas-redirect/", views.campanhas, name="campanhas"),
    path("pecas-criativos/", views.pecas_criativos, name="pecas_criativos"),
    path("pecas-criativos/<int:cliente_id>/", views.pecas_campanhas, name="pecas_campanhas"),
    path("veiculacao/", views.veiculacao, name="veiculacao"),
    path("veiculacao/google-ads/", views.veiculacao, name="veiculacao_google", kwargs={"platform": "google"}),
    path("veiculacao/meta-ads/", views.veiculacao, name="veiculacao_meta", kwargs={"platform": "meta"}),
    path("dashon/", views.dashon, name="dashon"),
    path("relatorios/", views.relatorios, name="relatorios"),
    path("relatorios/clientes/", views.relatorios_clientes, name="relatorios_clientes"),
    path("relatorios/clientes/<int:cliente_id>/", views.relatorios_campanhas, name="relatorios_campanhas"),
    path("relatorios/consolidado/", views.relatorios_consolidado, name="relatorios_consolidado"),
    path("analytics/", views.analytics, name="analytics"),
    path("integracoes/", views.integracoes, name="integracoes"),
    path("integracoes/google-ads/auth-url/", views.gads_auth_url, name="gads_auth_url"),
    path("integracoes/google-ads/callback/", views.gads_callback, name="gads_callback"),
    path("integracoes/google-ads/<int:account_id>/disconnect/", views.gads_disconnect, name="gads_disconnect"),
    path("integracoes/google-ads/<int:account_id>/sync/", views.gads_sync, name="gads_sync"),
    path("integracoes/google-ads/clear-logs/", views.gads_clear_logs, name="gads_clear_logs"),
    path("integracoes/google-ads/clear-data/", views.gads_clear_data, name="gads_clear_data"),
    path("integracoes/meta-ads/auth-url/", views.mads_auth_url, name="mads_auth_url"),
    path("integracoes/meta-ads/callback/", views.mads_callback, name="mads_callback"),
    path("integracoes/meta-ads/<int:account_id>/disconnect/", views.mads_disconnect, name="mads_disconnect"),
    path("integracoes/meta-ads/<int:account_id>/sync/", views.mads_sync, name="mads_sync"),
    path("integracoes/meta-ads/clear-logs/", views.mads_clear_logs, name="mads_clear_logs"),
    path("integracoes/meta-ads/clear-data/", views.mads_clear_data, name="mads_clear_data"),
    path("api/veiculacao-data/", views.api_veiculacao_data, name="api_veiculacao_data"),
    path("uploads-planilhas/", views.uploads_planilhas, name="uploads_planilhas"),
    path("uploads-midia/", views.uploads_midia_clientes, name="uploads_midia_clientes"),
    path("uploads-midia/clientes/<int:cliente_id>/", views.uploads_midia_campanhas, name="uploads_midia_campanhas"),
    path("uploads-midia/campanhas/<int:campaign_id>/", views.uploads_midia_pecas, name="uploads_midia_pecas"),
    path("api/pieces/<int:piece_id>/upload/", views.api_upload_piece_asset, name="api_upload_piece_asset"),
    path("api/pieces/<int:piece_id>/", views.api_piece_update, name="api_piece_update"),
    path("api/campaigns/<int:campaign_id>/pieces/", views.api_piece_create, name="api_piece_create"),
    path("usuarios-permissoes/", views.usuarios_permissoes, name="usuarios_permissoes"),
    path("clientes/", views.clientes_list, name="clientes"),
    path("clientes/novo/", views.clientes_create, name="clientes_create"),
    path("clientes/<int:cliente_id>/", views.clientes_detail, name="clientes_detail"),
    path("clientes/<int:cliente_id>/campanhas/", views.cliente_campaigns, name="cliente_campaigns"),
    path("clientes/<int:cliente_id>/editar/", views.clientes_edit, name="clientes_edit"),
    path("clientes/<int:cliente_id>/entrar/", views.clientes_enter, name="clientes_enter"),
    path("clientes/<int:cliente_id>/upload/", views.clientes_upload, name="clientes_upload"),
    path("sair-visao-cliente/", views.sair_visao_cliente, name="sair_visao_cliente"),
    path("api/set-selected-cliente/", views.set_selected_cliente, name="set_selected_cliente"),
    path("contratos/upload/", views.contract_wizard_entry, name="contract_wizard_entry"),
    path("clientes/<int:cliente_id>/contratos/upload/", views.contract_wizard_step1, name="contract_wizard_step1"),
    path("contratos/upload/<int:campaign_id>/arquivo/", views.contract_wizard_step2, name="contract_wizard_step2"),
    path("contratos/upload/<int:campaign_id>/concluido/", views.contract_done, name="contract_done"),
    path(
        "campanhas/<int:campaign_id>/plano-midia/upload/",
        views.campaign_media_plan_upload,
        name="campaign_media_plan_upload",
    ),
    path(
        "campanhas/<int:campaign_id>/pecas/upload/",
        views.campaign_assets_upload,
        name="campaign_assets_upload",
    ),
    path(
        "campanhas/<int:campaign_id>/vinculacao/",
        views.campaign_link_matrix,
        name="campaign_link_matrix",
    ),
    path("campanhas/<int:campaign_id>/detalhe/", views.campanha_detalhe, name="campanha_detalhe"),
    path("pecas/<int:piece_id>/", views.peca_detalhe, name="peca_detalhe"),
    path("campanhas/<int:campaign_id>/editar/", views.campaign_edit, name="campaign_edit"),
    path("campanhas/<int:campaign_id>/excluir/", views.campaign_delete, name="campaign_delete"),
    path(
        "campanhas/<int:campaign_id>/status/",
        views.campaign_set_status,
        name="campaign_set_status",
    ),
    path("api/campaigns/<int:campaign_id>/", views.api_campaign_detail, name="api_campaign_detail"),
    path("api/campaigns/<int:campaign_id>/region-investments/", views.api_region_investments, name="api_region_investments"),
    path("api/login/", views.api_login, name="api_login"),
    path("api/logout/", views.api_logout, name="api_logout"),
    path("api/me/", views.api_me, name="api_me"),
    path("api/users/", views.api_users, name="api_users"),
    path("api/users/<int:user_id>/", views.api_user_detail, name="api_user_detail"),
    path("api/alertas/<int:alerta_id>/lido/", views.api_alerta_lido, name="api_alerta_lido"),
    path("configuracoes/", views.configuracoes, name="configuracoes"),
    path("logs-auditoria/", views.logs_auditoria, name="logs_auditoria"),
]
